/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simuladorcarro.GUI;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import simuladorcarro.modelos.SimuladorCarro;

/**
 *
 * @author Marco Sanint
 */
public class MainWindow extends javax.swing.JFrame {

    private SimuladorCarro CS;
    private FondoPanel fondo;
    
    /**
     * Creates new form NewJFrame
     */
    public MainWindow() {
        initComponents();
        
        fondo = new FondoPanel();
        add(fondo);
    }
    
        
    public void printVel(){
        if(CS.getCar().isEstado() == true){
            Velocimetro.setText("  " + CS.getCar().getVelocidad());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bAcelerar = new javax.swing.JButton();
        bFrenarSup = new javax.swing.JButton();
        bFrenarInf = new javax.swing.JButton();
        bOffCar = new javax.swing.JButton();
        bOnCar = new javax.swing.JButton();
        Km = new javax.swing.JLabel();
        Velocimetro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondoCarro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bAcelerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladorcarro/imagenes/pedal.png"))); // NOI18N
        bAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcelerarActionPerformed(evt);
            }
        });
        jPanel1.add(bAcelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 30, 40));

        bFrenarSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladorcarro/imagenes/PedalStopSup.png"))); // NOI18N
        bFrenarSup.setContentAreaFilled(false);
        bFrenarSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFrenarSupActionPerformed(evt);
            }
        });
        jPanel1.add(bFrenarSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 30, 20));

        bFrenarInf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladorcarro/imagenes/PedalStopInf.png"))); // NOI18N
        bFrenarInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFrenarInfActionPerformed(evt);
            }
        });
        jPanel1.add(bFrenarInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 30, 20));

        bOffCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladorcarro/imagenes/llavesOff.png"))); // NOI18N
        bOffCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOffCarActionPerformed(evt);
            }
        });
        jPanel1.add(bOffCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 30, 30));

        bOnCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladorcarro/imagenes/llaves.png"))); // NOI18N
        bOnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOnCarActionPerformed(evt);
            }
        });
        jPanel1.add(bOnCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 30, 30));

        Km.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Km.setForeground(new java.awt.Color(255, 255, 51));
        jPanel1.add(Km, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 40, 30));

        Velocimetro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Velocimetro.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(Velocimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladorcarro/imagenes/negro.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 100, 40));

        fondoCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladorcarro/imagenes/parteInternaCarro.png"))); // NOI18N
        jPanel1.add(fondoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOnCarActionPerformed
        Km.setText("km/h");
        Velocimetro.setText("  0");
        CS.prenderCarro();
    }//GEN-LAST:event_bOnCarActionPerformed

    private void bOffCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOffCarActionPerformed
        Km.setText("");
        Velocimetro.setText("");
        CS.apagarCarro();
    }//GEN-LAST:event_bOffCarActionPerformed

    private void bAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcelerarActionPerformed
        CS.acelerarCarro();
        printVel();
        if(CS.getCar().isEstado() == false){
            Km.setText("");
            Velocimetro.setText("");
        }
    }//GEN-LAST:event_bAcelerarActionPerformed

    private void bFrenarSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFrenarSupActionPerformed
        CS.frenarCarro();
        printVel();
    }//GEN-LAST:event_bFrenarSupActionPerformed

    private void bFrenarInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFrenarInfActionPerformed
        CS.frenarBruscoCarro();
        printVel();
    }//GEN-LAST:event_bFrenarInfActionPerformed

    class FondoPanel extends JPanel {
        private Image imagen;

        public FondoPanel() {
            // Cargar la imagen de fondo en el constructor
            imagen = new ImageIcon(getClass().getResource("/simuladorcarro/imagenes/parteInternaCarro.png")).getImage();
        }

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            // Dibujar la imagen de fondo en el panel
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
    
    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        MainWindow MW = new MainWindow();
        SimuladorCarro CS = new SimuladorCarro();
        
        MW.setCarSimulator(CS);

        MW.setTitle("Car Simulator");
        MW.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Km;
    private javax.swing.JLabel Velocimetro;
    private javax.swing.JButton bAcelerar;
    private javax.swing.JButton bFrenarInf;
    private javax.swing.JButton bFrenarSup;
    private javax.swing.JButton bOffCar;
    private javax.swing.JButton bOnCar;
    private javax.swing.JLabel fondoCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the car
     */
    public SimuladorCarro getCarSimulator() {
        return CS;
    }

    /**
     * @param car the car to set
     */
    public void setCarSimulator(SimuladorCarro car) {
        this.CS = car;
    }
}
